name: checker
on: [push]

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Ruff
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install ruff
          ruff check
          ruff format --check

  cspell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cspell via Docker
        run: |
          docker run --rm -v "$PWD":/app ghcr.io/streetsidesoftware/cspell:latest -c cspell.json --file src/*.py
